INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Bacitracin', 'P01AX06', 'Atovaquone');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Baclofen', 'N07XX05', '3,4- diaminopyridine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Bactrim', 'L01XD04', '5-Aminolevulinic acid');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Bactrim DS', 'D05BA02', '8-Methoxypsoralen ');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Bactroban', 'J05AR02', 'Abacavir, lamivudine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Basaglar', 'L01XE', 'Abemaciclib');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Belbuca', 'C07AB04', 'Acebutolol hydrochloride');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Belsomra', 'B01AA07', 'Acenocoumarol');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Benadryl', 'A05AA03', 'Acide cholique');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Benazepril', 'C01BA05', 'Ajmaline');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Benicar', 'L01CD',    'Albumin Bound Paclitaxel');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Bentyl', 'B05AA01', 'Albumin human');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Benzonatate', 'L01XC04', 'Alemtuzumab');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Benztropine', 'A16AB07', 'Alglucosidase alfa');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Betamethasone', 'M04AA01', 'Allopurinol');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Bethanechol', 'C01EA01', 'Alprostadil (Prostaglandin E1');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Bevacizumab', 'N04BB01', 'Amantadine hydrochloride');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Biaxin', 'N07AA30', 'Ambenonium Chloride');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Bicalutamide', 'V03AF05', 'Amifostine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Biktarvy', 'C03EA01', 'Amilorid, Hydroklorotiyazid');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Biotin', 'C03DB01', 'Amiloride');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Bisacodyl', 'D11AX',    'Aminobenzoate potassium');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Bismuth subsalicylate', 'N05CA02', 'Amobarbital sodium');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Bisoprolol', 'N06BA01', 'Amphetamine, dextroamphetamine mixed salts');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Boniva', 'L01XX01', 'Amsacrine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Botox', 'V03AB22', 'Amyl nitrite');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Breo Ellipta', 'L04AC03', 'Anakinra');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Brilinta', 'G03BB02', 'Androstanolone');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Brimonidine', 'B01AB02', 'Antithrombin III');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Budesonide', 'L04AA03', 'Anti-thymocyte globulin (Lymphocyte immune globulin)(HORSE');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Budesonide and Formoterol', 'S01AE03', 'Apraclonidine hydrochloride');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Bumetanide', 'B02AB01', 'Aprotinin');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Bumex', 'B05XB01', 'Arginine hydrochloride');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Buprenorphine', 'P01BF01', 'Artemether and Lumefantrine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Buprenorphine and Naloxone', 'P01BE03', 'Artesunate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Bupropion', 'N05AH05', 'Asenapine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Buspar', 'A16AB13', 'Asfotase alfa');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Buspirone', 'L01XX02', 'Asparaginase erwinia chrysanthemi');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Debrox', 'P01BB51', 'Atovaquone and proguanil hydrochloride');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Decadron', 'J01DF01', 'Aztreonam');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Demerol', 'L03AX03', 'Bacillus Calmette-Guerin(BCG) strains');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Denosumab', 'M03BX01', 'Baclofen');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Depakote', 'N03AA04', 'Barbexaclone ');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Depo-Provera', 'V08BA02', 'Barium sulfate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Desloratadine', 'C04AX11', 'Bencyclane hydrogen fumarate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Desvenlafaxine', 'N04AC01', 'Benztropine Mesylate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Dexamethasone', 'A16AA06', 'Betaine anhydrous');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Dexilant', 'A16AA06', 'Betaine hydrochloride');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Dextroamphetamine', 'N07AB02', 'Bethanechol Chloride');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Dextromethorphan', 'L01XX25', 'Bexarotene');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Diazepam', 'C10AB02', 'Bezafibrate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Diclofenac', 'A06AG02', 'Bisacodyl');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Diclofenac Sodium', 'L01XE14', 'Bosutinib');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Dicyclomine', 'L01XE43', 'Brigatinib');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Diflucan', 'N03AX23', 'Brivaracetam');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Digoxin', 'A07EA06', 'Budesonide (extended release tablet');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Dilantin', 'C03CA02', 'Bumetanide');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Dilaudid', 'M05BX05', 'Burosumab');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Diltiazem', 'L01XE', 'Cabozantinib');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Diovan', 'B05XA07', 'Calcium chloride');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Diphenhydramine', 'N02BG10', 'Cannabidiol');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Ditropan', 'J04AB30', 'Capreomycin Sulfate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Divalproex', 'N01BX04', 'Capsaicin');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Divalproex sodium', 'N04BA02', 'Carbidopa- levodopa, Levodopa - Carbidopa');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Docusate', 'G02AD04', 'Carboprost tromethamine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Docusate Sodium', 'A16AA05', 'Carglumic Acid');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Domperidone', 'L01AD01', 'Carmustine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Donepezil', 'J01DD52', 'Ceftazidime and avibactam');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Doxazosin', 'L01XC',   'Cemiplimab');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Doxepin', 'A16AB17', 'Cerliponase alfa (intraventricular injection');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Doxycycline', 'N07AX03', 'Cevimeline hydrochloride');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Dulcolax', 'A05AA01', 'Chenodeoxycholic Acid');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Dulera', 'C03AA04', 'Chlorothiazide');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Duloxetine', '10BB02', 'Chlorpropamide');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'DuoNeb', 'A16AX', 'Cholesterol');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Dupixent', 'V06DX', 'Cholesterol, Carbonhydrate (Cholesterol, Dried Glucose Syrup');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Dutasteride', 'A13A', 'Citrulline malate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Dyazide', 'N05BA09', 'Clobazam');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Echinacea', 'J04BA01', 'Clofazimine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Ecotrin', 'C02AC01', 'Clonidine hydrochloride');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Effexor', 'B02BD13', 'Coagulation Factor X (Human');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Effexor XR', 'C01EB09', 'Coenzyme Q10');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Effient', 'M04AC01', 'Colchicine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Elavil', 'D03BA02', 'Collagenase');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Eligard', 'M09AB02', 'Collagenase clostridium histolyticum');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Eliquis', 'G03CA57', 'Conjugated estrogens');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Elmiron', 'V04CD04', 'Corticorelin Trifluoroacetate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Emgality', 'A16', 'Creatinine Monohydrate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Empagliflozin', 'A07EB01', 'Cromolin sodium');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Enalapril', 'A16AA04', 'Cysteamine bitartrate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Enbrel', 'S01XA21', 'Cysteamine hydrochloride');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Enoxaparin', 'L01BC', 'Cytarabine liposome injection');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Entecavir', 'J06BB09', 'Cytomegalovirus immunglobulin');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Entresto', 'V06DC', 'D- Mannose');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Entyvio', 'L01DA01', 'Dactinomycin');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Epclusa', 'M03CA01', 'Dantrolene Sodium');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Ephedrine', 'J04BA02', 'Dapsone');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Epidiolex', 'J04BA', 'Dapsone and rifampicin');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Epinephrine', 'L01XY01', 'Daunorubicin - Cytarabine (Lipozomal');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'EpiPen', 'L01DB02', 'Daunorubicin citrate liposomal');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Eplerenone', 'B01AX01', 'Defibrotide');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Ergocalciferol', 'J04AK06', 'Delamanid');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Ertapenem', 'H01BA02', 'Desmopressin acetate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Erythromycin', 'N07XX', 'Deutetrabenazine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Escitalopram', 'S01XA20', 'Dextran 70, Hypromellose');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Esomeprazole', 'R05DA09', 'Dextromethorphan hydrobromide');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Estrace', 'N07XX59 ', 'Dextromethorphan hydrobromide and quinidine sulfate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Estradiol', 'V03AH01', 'Diazoxide');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Eszopiclone', 'C01AA04', 'Digitoxine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Ethambutol', 'V03AB24', 'Digoxin-immune ovine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Etodolac', 'N02CA01', 'Dihydroergotamine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Eucrisa', 'P03AX05', 'Dimethicone');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Evista', 'G04BX13', 'Dimethyl Sulfoxide');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Excedrin', 'L01XC16', 'Dinutuximab');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Exelon', 'L01XC16', 'Dinutuximab Beta');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Exemestane', 'B01AC07', 'Dipyridamole');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Exforge', 'G04BC', 'Disodium hydrogenphosphate, potassium dihidrogen phosphate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Ezetimibe', 'C01BA03', 'Disopyramide phosphate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Jadelle', 'N07AA03', 'Distigmine Bromide');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Jadenu', 'N07BB01', 'Disulfiram');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Jakafi', 'S01EC03', 'Dorzolamide');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Jalyn', 'S01ED51', 'Dorzolamide hydrochloride and timolol maleate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Jantoven', 'N06AA12', 'Doxepin hydrochloride');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Janumet', 'M01CC01', 'D-Penicillamine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Janumet XR', 'C01BD07', 'Dronedarone hydrochloride');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Januvia', 'C01CA', 'Droxidopa');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Jardiance', 'D11AH05', 'Dupilumab');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Jatenzo', 'L01XC28', 'Durvalumab');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Jencycla', 'B06AC03', 'Ecallantide');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Jentadueto', 'N07XX', 'Edaravone');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Jentadueto XR', 'B02BD04 ', 'Eftrenonacog alfa');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Jetrea', 'A16AB', 'Elosulfase Alfa');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Jeuveau', 'L01XC23', 'Elotuzumab');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Jevtana', 'B02BX06', 'Emicizumab');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Jiaogulan', 'J05AF09', 'Emtricitabine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Jinteli', 'J05AX07', 'Enfuvirtide');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Jolessa', 'J05AF10', 'Entecavir');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Jolivette', 'B01AC09', 'Epoprostenol sodium');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Jornay PM', 'L01XX41', 'Eribulin mesylate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Jublia', 'J01FA01', 'Erythromycin');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Juleber', 'G03CA01', 'Ethinyl estradiol');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Juluca', 'V08AD01', 'Ethiodized oil');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Junel', 'N03AD01', 'Ethosuximide');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Junel 1/20', 'C01CA01', 'Etilefrin hydrochlorid');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Junel Fe 1/20', 'N01AX07', 'Etomidate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Junel Fe 1.5/30', 'C10AX13', 'Evolocumab');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Junel Fe 24', 'N03AX21', 'Ezogabine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Juvederm', 'V06DB', 'Fat/carbohydrates/proteins/minerals/vitamins, combinations');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Juxtapid', 'M04AA03', 'Febuxostat (40 mg)');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Jynarque', 'N03AX10', 'Felbamate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Kadcyla', 'C01BC04', 'Flecainide Acetate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Kadian', 'J02AX01', 'Flucytosine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Kaletra', 'H02AA02', 'Fludrocortisone acetate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Kaopectate', 'L02BB01', 'Flutamide');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Kapvay', 'V03AB34', 'Fomepizole');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Kariva', 'J05AD01', 'Foscarnet Sodium');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Kava', 'B02BX09  ', 'Fostamatinib  disodium hexahydrate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Kayexalate', 'D05BX51', 'Fumaric acid esters');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Kcentra', 'C03CA01', 'Furosemide');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'K-Dur', 'A16AB08', 'Galsulfase');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Keflex', 'L01BC05', 'Gemcitabine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Kenalog', 'L01XC05', 'Gemtuzumab ozogamicin');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Kenalog-40', 'B05BA02', 'Glicerol trioleate oil');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Keppra', 'V03AF09', 'Glucarpidase');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Keppra XR', 'V06DC01', 'Glucose anhydrous');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Ketamine', 'V03AB32', 'Glutathione');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Ketoconazole', 'V06DX', 'Glycine free powdered infant formula');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Ketoconazole Cream', 'V06DB', 'Glycomacropeptide and essential amino acids');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Ketoconazole Shampoo', 'A03AB02', 'Glycopyrrolate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Ketoconazole topical', 'A03AB02', 'Glycopyrronium bromide ');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Ketoprofen', 'M01CB01', 'Gold sodium aurothiomalate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Ketorolac', 'H01CA01 ', 'Gonadorelin acetate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Ketorolac ophthalmic', 'A04AA02', 'Granisetron');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Ketorolac Tromethamine', 'D01AA08', 'Griseofulvin');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Ketotifen', 'S01EX01', 'Guanethidine monosulfate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Ketotifen ophthalmic', 'C02AC02', 'Guanfacine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Kevzara', 'B02BD', 'Human coagulation factor XI');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Keytruda', 'B02BD07', 'Human coagulation factor XIII');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Kineret', 'B06AB', 'Human hemin');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Kisqali', 'J07BG01 ', 'Hucre kulturunden uretilen inaktif kuduz virusu');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Klonopin', 'B06AA03', 'Hyaluronidase');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Klor-Con', 'C02DB02', 'Hydralazine HCl');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Kombiglyze XR', 'C03AA03', 'Hydrochlorothiazide');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Korlym', 'H02AB09', 'Hydrocortisone');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Kratom', 'N02AA03', 'Hydromorphone hydrochloride');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Krill Oil', 'C01BA', 'Hydroquinidine hydrochloride');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Krystexxa', 'V03AB33', 'Hydroxocobalamin');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'K-Tab', 'V06', 'Hydroxybutyric acid');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Kyleena', 'P01BA02', 'Hydroxychloroquine sulphate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Kyprolis', 'N06BX13', 'Idebenone');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Macrobid', 'A16AB09', 'Idursulfase');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Magnesium', 'A16AB09', 'Idursulfase beta');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Magnesium citrate', 'G04BX', 'Immunomodulatory fractions extracted from E. coli in a lyophilized form');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Magnesium oxide', 'J07BF03', 'Inactivated polio vaccine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Meclizine', 'V04CH02', 'Indigotindisulfonate sodium');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Medrol', 'C01EB03', 'Indometacin');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Medrol Dosepak', 'J05AX05', 'Inosine pranobex');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Melatonin', 'L01XC26', 'Inotuzumab ozogamicin');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Meloxicam', 'A10AE06', 'Insulin degludec');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Memantine', 'L03AB03', 'Interferon gamma');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Meropenem', 'V08AD01', 'Iodised ethyl-esters of the fatty acids of poppy seed oil');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Mesalamine', 'V09AB03', 'Ioflupane I123');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Metamucil', 'R01AX03', 'Ipratropium bromide');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Metformin', 'A16AA', 'Isoleucine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Methadone', 'C01CA02', 'Isoproterenol hydrochloride');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Methimazole', 'R07AX02', 'Ivacaftor');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Methocarbamol', 'R07AX30', 'Ivacaftor and lumacaftor');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Methotrexate', 'R07AX31 ', 'Ivacaftor Ivacaftor, tezacaftor')
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Methylphenidate', 'P02CF01', 'Ivermectin');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Methylprednisolone', 'P02CF01', 'Ivermectin');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Metoclopramide', 'L01DC04', 'Ixabepilone');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Metolazone', 'L01XX47', 'Ä°delalisib');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Metoprolol', 'A10AB01', 'Ä°nsulin (human');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Metoprolol Tartrate', 'J06AA06 ', 'Kuduz antiserumu');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Metronidazole', 'V06DD', 'L- Citrulline');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Midazolam', 'C07AG01', 'Labetalol');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Midodrine', 'A16AX', 'Large Neutral Amino Acids');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Minocycline', 'A16AA', 'L-Arginine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'MiraLAX', 'A16AA', 'L-Asparagine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Mirapex', 'L01XE29', 'Lenvatinib mesylate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Mirtazapine', 'N04BA02', 'Levodopa, carbidopa monohydrate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Mobic', 'H03AA01', 'Levothyroxine sodium');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Modafinil', 'A16AA03', 'L-glutamine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Montelukast', 'A16AA', 'L-Glycine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Morphine', 'D04AB01', 'Lidocaine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Motrin', 'L01XX19', 'Liposomal irinotecan hydrochloride');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Mucinex', 'G02CB02', 'Lisuride hydrogen maleate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Mupirocin', 'N05AN01', 'Lithium Carbonate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Mupirocin topical', 'J07BF04 ', 'Live attenuated poliomyelitis virus  strains type 1 and type 3 ');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Myrbetriq', 'V06DD', 'L-Lysine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Ocrelizumab', 'C10AX12', 'Lomitapide');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Ocrevus', 'L01AD02', 'Lomustine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Octreotide', 'J05AR10', 'Lopinavir, ritonavir');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Ocuflox', 'L01XE44', 'Lorlatinib');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Ocuvite', 'A05BA06', 'L-ornithine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Ofev', 'C10AA02', 'Lovastatin');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Ofloxacin', 'C10AA09', 'L-Serine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Ofloxacin ophthalmic', 'V03AF02', 'Lyophilized dexrazoxane');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Olanzapine', 'A16AX', 'Lysine and Vitamin B12 & B6');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Olaparib', 'A12CC04', 'Magnesium');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Olmesartan', 'A12CC01', 'Magnesium Chloride');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Olmesartan Medoxomil', 'A12CC04', 'Magnesium citrate, Magnesium ( hydrogen- L-glutamate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Omalizumab', 'R05CB16', 'Mannitol');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Omega-3 polyunsaturated fatty acids', 'H01AC03', 'Mecasermin');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Omeprazole', 'L01AA05', 'Mechlorethamine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Omnicef', 'B05BA02', 'Medium chain triglycerides');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Ondansetron', 'G03DA02', 'Medroxyprogesterone acetate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Onfi', 'P01BC02', 'Mefloquine hydrochloride');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Onglyza', 'P01CB01', 'Meglumine antimoniate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Opana', 'L01AA03', 'Melphalan');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Opdivo', 'L04AC06', 'Mepolizumab');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Opium', 'L01BB02', 'Mercaptopurine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Orencia', 'V03AF01', 'Mesna');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Orlistat', 'S01EC05', 'Methazolamide');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Orphenadrine', 'V03AB26', 'Methionine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Ortho Tri-Cyclen', 'C03BA08', 'Metolazone');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Oseltamivir', 'V04CD01', 'Metyrapone');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Otezla', 'C01BB02', 'Mexiletine hydrochloride');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Oxaliplatin', 'N05CD08', 'Midazolam');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Oxazepam', 'C01CA17', 'Midodrine hydrochloride');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Oxcarbazepine', 'A16A', 'Migalastat');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Oxybutynin', 'L04AA06', 'Mikofenolat mofetil');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Oxycodone', 'B05BA02', 'Milk based with %84 MCT oil');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Oxycodone Hydrochloride', 'N06AX17', 'Milnacipran hydrochloride');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Oxycontin', 'L01XX09', 'Miltefosine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Oxygen', 'J01AA08', 'Minocycline');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Oxymetazoline nasal', 'C02DC01', 'Minoxidil');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Oxymorphone', 'L01DC03', 'Mitomycin (2 mg');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Oxytocin', 'L01XX23', 'Mitotane');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Ozempic', 'L01XC25 ', '"Mogamulizumab"');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Salbutamol', 'D11AX13', 'Monobenzone(monobenzyl ether of hydroquinone)';
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Saw Palmetto', 'A11JA', 'Multivitamins (A,D,E,K');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Saxenda', 'A11JB', 'Multivitamins (A,D,E,K) and minerals');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Scopolamine', 'C07AA12', 'Nadolol');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Selenium', 'H01CA02', 'Nafarelin acetate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Senna', 'C04AX21', 'Naftidrofuryl oxalate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Senokot', 'N07BB05', 'Nalmefene');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Sensipar', 'V03AB15', 'Naloxone hydrochloride');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Septra', 'N02AA55', 'Naloxone hydrochloride and Oxycodone hydrochloride');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Seroquel', 'N07BB04', 'Naltrexone hydrochloride');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Sertraline', 'N07BB04', 'Naltrexone hydrochloride');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Sevelamer', 'S01AA10', 'Natamycin');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Shingrix', 'A07EA01', 'Natrium(prednisolon-21-succinat');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Sildenafil', 'A12CD01', 'Natriumfluorid');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Simethicone', 'L01BB07', 'Nelarabine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Simvastatin', 'B05CA09', 'Neomycin sulfate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Sinemet', 'L01XE', 'Neratinib maleate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Singulair', 'J05AG01', 'Nevirapine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Sitagliptin', 'C01DX16', 'Nicorandil');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Skelaxin', 'A11HA01', 'Nicotinamide(Nicotinic acid');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Sodium bicarbonate', 'L01XC', 'Nimotuzumab');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Sodium chloride', 'L01XX54', 'Niraparib tosylate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Solifenacin', 'C04AE02', 'Nisergolin');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Solu-Medrol', 'P01AX11', 'Nitazoxanide');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Soma', 'C08CA08', 'Nitrendipine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Sotalol', 'J01XE01', 'Nitrofurantoin');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Spiriva', 'C02DD01', 'Nitroprussid natrium');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Spironolactone', 'N07XX', 'Nusinersen Sodium');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Stelara', 'B05BA02', 'Nutrients, vitamins, minerals with % 90 MCT oil');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Strattera', 'A05AA04', 'Obeticholic acid');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Suboxone', 'V03AB13', 'Obidoxime Chloride');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Subutex', 'L01XC10', 'Ofatumumab');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Sucralfate', 'L01XX46', 'Olaparib ');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Sudafed', 'L01XC', 'Olaratumab');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Sulfamethoxazole and trimethoprim', 'A07EC03', 'Olsalazine sodium');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Sulfasalazine', 'A14AA20', 'Orexin (Hypocretin');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Sumatriptan', 'A14AA08', 'Oxandrolone');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Symbicort', 'N06AX01', 'Oxitriptan');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Synthroid', 'L01XE33', 'Palbociclib');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Systane', 'A09AA02', 'Pancreatic enzymes');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Ubiquinone', 'L01XX42', 'Panobinostat');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Uceris', 'J04AA01', 'Para-aminosalicylic acid');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Udenyca', 'A07AA06', 'Paromomycin');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Ulesfia', 'H01CB05', 'Pasireotide pamoate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Ulipristal', 'L03AX04', 'Pegademase bovine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Uloric', 'L01XX24', 'Pegaspargase');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Ultomiris', 'M04AX02', 'Pegloticase ');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Ultracet', 'V04CG04', 'Pentagastrin');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Ultram', 'P01CX01', 'Pentamidine isethionate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Ultram ER', 'L01XX08', 'Pentostatin');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Ultravate', 'N07X', 'Peptide porcine brain extract (Proteolytic peptid fraction derive from protein of Porcine brain');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Ultresa', 'N03AX22', 'Perampanel');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Umeclidinium', 'N03AA02', 'Phenobarbital');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Umeclidinium and vilanterol', 'C04AX02', 'Phenoxybenzamine hydrochloride');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Unasyn', 'B01AA04', 'Phenprocoumon');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Undecylenic acid topical', 'C04AB01', 'Phentolamine Mesylate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Unisom', 'C01CA06', 'Phenylephrine hydrochloride');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Unisom SleepMelts', 'A12CX', 'Phosphate salts, Phosphorus, Sodium, Potassium');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Unithroid', 'S01EB05', 'Physostigmine salicylate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Univasc', 'B02BA01', 'Phytomenadione (K1 Vitamini');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Upadacitinib', 'L01DC', 'Picibanil (OK-432');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Uptravi', 'N07AX01', 'Pilocarpine hydrochloride');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Ureacin-10', 'S01EB01', 'Pilocarpine hydrochloride');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Urea Cream', 'L01DB11', 'Pixantrone');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Urecholine', 'D06BB04', 'Podofilox');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Uribel', 'L01XE24', 'Ponatinib');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Urimar-T', 'N05CM11', 'Potassium bromide');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Urin D/S', 'A12BA01', 'Potassium chloride');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Urispas', 'S01XA', 'Potassium iodide, sodium iodide');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Uristat', 'G04BC', 'Potassium sodium hydrogen citrate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Urocit-K', 'L01BA05', 'Pralatrexate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Urogesic-Blue', 'P02BA01', 'Praziquantel');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Urokinase', 'P01BA03', 'Primaquine phosphate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Uro-MP', 'M04AB01', 'Probenecid');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Uroxatral', 'L01XB01', 'Procarbazine hydrochloride');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Urso', 'C01BC03 ', 'Propafenone hydrochloride');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Ursodiol', 'S01AX15', 'Propamidine Ä°sethionate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Ustekinumab', 'C07AA05', 'Propranolol hydrochloride');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Utibron Neohaler', 'G02AD01', 'Prostaglandin F2 alpha');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Uva Ursi', 'B01AD12', 'Protein C concentrate (Human');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Valacyclovir', 'N07AA02', 'Pyridostigmine bromide ');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Valium', 'A11HA06', 'Pyridoxal-5-phosphate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Valproic acid', 'A11HA02', 'Pyridoxine (Vitamin B6');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Valsartan', 'P01BD01', 'Pyrimethamine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Valtrex', 'N06BX02', 'Pyritinol dihydrochloride');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Vancomycin', 'C01BA01', 'Quinidin sulphate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Varenicline', 'P01BC01', 'Quinine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Vascepa', 'L04AA04', 'Rabbit anti-human thymocyte immunoglobulin');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Vasopressin', 'L01XC', 'Racotumomab');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Vasotec', 'L01BA03', 'Raltitrexed');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Veltassa', 'N03AX21', 'Retigabine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Venlafaxine', 'V10AX05', 'Rhenium (186Re) sulfide colloid');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Venofer', 'A11HA04', 'Riboflavin (Vitamin B2');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Ventolin', 'J04BA', 'Rifampicin, dapsone and clofazimine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Ventolin HFA', 'J04AB05', 'Rifapentine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Verapamil', 'S01BA13', 'Rimexolone');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Versed', 'L01XX39', 'Romidepsin');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'VESIcare', 'B02BX04', 'Romiplostim');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Viagra', 'N04BC09', 'Rotigotine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Viberzi', 'N03AF03', 'Rufinamide');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Vibramycin', 'A16AB06', 'Sacrosidase');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Vicodin', 'A16AA02', 'S-adenosylmethionine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Victoza', 'V10BX02', 'Samarium (153Sm) lexidronam');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Vigamox', 'L03AA09', 'Sargramostim');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Viibryd', 'A04AD01', 'Scopolamine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Vimpat', 'A16AB14', 'Sebelipase alfa');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Vistaril', 'N04BD01', 'Selegiline');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Vitamin B 12', 'V04CD03', 'Sermorelin acetate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Vitamin C', 'A05BA03', 'Silibinin disodium disuccÄ±inate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Vitamin D', 'L04AC11', 'Siltuximab');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Vitamin D2', 'A16AX', 'Sodium benzoate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Vitamin D3', 'A14AZ08', 'Sodium chloride, potassium chloride, potassium hydrogen 2-ketoglutarate, magnesium chloride histidine, tryptophan, mannitol and calcium chloride');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Vitamin E', 'A06AD65', 'Sodium chloride, Sodium bicarbonate, Potassium chloride, macrogol');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Vivitrol', 'G01AD', 'Sodium Dichloroacetate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Voltaren', 'V03AB', 'Sodium Nitrite,Sodium Thiosulfate and Amyl Nitrite');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Voltaren Gel', 'A16AX', 'Sodium phenylacetate and Sodium benzoate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Vortioxetine', 'A16AX03', 'Sodium Phenylbutyrate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Vraylar', 'A12CX', 'Sodium phosphate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Vytorin', 'A12CX', 'Sodium phosphate monobasic');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Vyvanse', 'V03AE01', 'Sodium polystrene sulfonate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Xadago', 'P01CB02', 'Sodium stibogluconate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Xalatan', 'C05BB04', 'Sodium tetradecyl sulfate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Xalkori', 'V03AB06', 'Sodium thiosulphate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Xanax', 'L01XX48', 'Sonidegib');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Xanax XR', 'A14AA02', 'Stanozolol');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Xarelto', 'N03AX17', 'Stiripentol');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Xeljanz', 'L01AD04', 'Streptozocine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Xeljanz XR', 'J01EC02', 'Sulfadiazine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Xeloda', 'P01BD51', 'Sulfadoksin, Pirimetamin');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Xenazine', 'M04AB02', 'Sulfinpyrazone ');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Xenical', 'M01AB02', 'Sulindac');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Xenleta', 'G02AD05', 'Sulprostone');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Xeomin', 'N03AX03', 'Sulthiame');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Xermelo', 'B02BD14', 'Susoctocog alfa');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Xgeva', 'M03AB01', 'Suxamethonium chloride');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Xhance', 'N07XX08', 'Tafamidis (as meglumine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Xiaflex', 'S01EE05', 'Tafluprost ');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Xifaxan', 'V09DA04', 'Technetium (99mTc) mebrofenin ');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Xigduo XR', 'A16AX08', 'Teduglutide');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Xiidra', 'L01BC53', 'Tegafur, Gimeracil and Oteracil potassium');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Xofigo', 'L01CB02', 'Teniposide');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Xofluza', 'R03CC03', 'Terbutaline sulfate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Xolair', 'G03BA03', 'Testosterone');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Xopenex', 'N07XX06', 'Tetrabenazine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Xopenex HFA', 'H01AA02', 'Tetracosactide');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Xospata', 'N02BG10', 'Tetrahydrocannabinol and cannabidiol');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Xpovio', 'A11DA01', 'Thiamin (Vitamin B1');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Xrylix', 'L01AC01', 'Thiotepa');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Xtampza ER', 'P01AB02', 'Tinidazole');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Xtandi', 'G04BC', 'Tiopronin');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Xulane', 'H03AA04', 'Tiratricol');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Xultophy', 'V04CJ01', 'Tirotropin alfa');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Xylitol', 'J01GB01', 'Tobramycin inhalation powder');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Xylocaine', 'C03CA04', 'Torasemide 200 mg');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Xylocaine Jelly', 'DSÃ– tarafÄ±ndan  ATC kodu henÃ¼z belirlenmemiÅŸ ilaÃ§', 'Tranilast');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Xylometazoline', 'L01XC03', 'Trastuzumab');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Xylometazoline nasal', 'L01AB02', 'Treosulfan');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Xyosted', 'B01AC21', 'Treprostinil Sodium');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Xyrem', 'L01XX14', 'Tretinoin');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Xyzal', 'C01DA52', 'Triacylglycerol forms of oleic acid and eruric acid');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Yarrow', 'P02BX04', 'Triclabendazole');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Yasmin', 'V03AB', 'Trientine dihydrochloride, Trientine hydrochloride');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Yaz', 'L01BC59', 'Trifluridine and tipiracil');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Yervoy', 'N04AA01', 'Trihexyphenidyl hydrochloride');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Yescarta', 'B05BB03', 'TromeThamine (2-amino-2-(hydroxymethyl)-1, 3-propanediol');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Yohimbe', 'A16AA', 'Tyrosine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Yohimbine', 'G03XB02', 'Ulipristal Acetate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Yondelis', 'S01EE02', 'Unoprostone isopropyl');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Yonsa', 'J05AB14 ', 'Valganciclovir hydrochloride');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Yosprala', 'A16AA', 'Valine');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Yupelri', 'L01XE12', 'Vandetanib');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Yuvafem', 'N07BC', 'Vanoxerin');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Zaditor', 'H01BA01', 'Vasopressin');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Zaleplon', 'A16AB15', 'Velmanase alfa');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Zanaflex', 'A16AB18 ', 'Vestronidase alfa');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Zantac', 'L01CA03', 'Vindesinsulfate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Zaroxolyn', 'A11CA01', 'Vitamin A Palmitate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Zarxio', 'L01XX38', 'Vorinostat');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Zebeta', 'B01AA03', 'Warfarin sodium');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Zegerid', 'B01AA03', 'Warfarin sodium');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Zenpep', 'V10AA01', 'Yttrium (90Y) citrate colloid');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Zestoretic', 'N05CF02', 'Zolpidem tartrate');
INSERT INTO ACTIVE_INGREDIENT ("mname", "atc_code", "atc_name") VALUES ( 'Zestril', 'N03AX15', 'Zonisamide');
