INSERT INTO HEALTH_INSTITUTION ("tax_no", "build_name", "address") VALUES ('6309227187', 'Atatürk Eğitim Ve Araştırma Hastanesi', 'Eskişehir Yolu 8.km No:2 Bilkent Ankara');
INSERT INTO HEALTH_INSTITUTION ("tax_no", "build_name", "address") VALUES ('1301713466', 'Dr. Zekai Tahir Burak Kadın Sağlığı Eğitim Ve Araştırma Hastanesi', 'Gündoğdu Mah. Karacaey Sokak Hamamönü Mamak Ankara');
INSERT INTO HEALTH_INSTITUTION ("tax_no", "build_name", "address") VALUES ('6670457814', 'Türkiye Yüksek İhtisas Eğitim Ve Araştırma Hastanesi', 'Ülkü Mah. Sıhhıye Ankara');
INSERT INTO HEALTH_INSTITUTION ("tax_no", "build_name", "address") VALUES ('2712899171', 'Ankara Ceza İnfaz Kurumları Kampüs Hastanesi', 'Sincan –Yenikent Ankara');
INSERT INTO HEALTH_INSTITUTION ("tax_no", "build_name", "address") VALUES ('5886307428', 'Bakırköy Devlet Hastanesi', 'Zuhuratbaba Mah., Dr. Tevfik Sağlam Cad., No:25/1, Bakırköy, İstanbul');
INSERT INTO HEALTH_INSTITUTION ("tax_no", "build_name", "address") VALUES ('5408874888', 'Beyoglu Hastanesi', 'Bereketzade Mah., Bereketzade Camii Sok., No:2, Beyoğlu, İstanbul');
INSERT INTO HEALTH_INSTITUTION ("tax_no", "build_name", "address") VALUES ('3589235960', 'Büyükada Devlet Hastanesi', 'Nizam Mah., Karakuş Sok., No:4/1, Adalar, İstanbul');
INSERT INTO HEALTH_INSTITUTION ("tax_no", "build_name", "address") VALUES ('2045374204', 'Çatalca Devlet ve Bölge Trafik Hastanesi', 'Ferhatpaşa Mahallesi İstanbul Caddesi No: 143 İstanbul');
INSERT INTO HEALTH_INSTITUTION ("tax_no", "build_name", "address") VALUES ('2907679107', 'Koşuyolu Kalp ve Araştırma Hastanesi', 'Cevizli Mah., Denizer Cad., No:2, Kartal, İstanbul');
INSERT INTO HEALTH_INSTITUTION ("tax_no", "build_name", "address") VALUES ('1663477853', 'PTT İçerenköy Hastanesi', 'Içerenköy Şubesi Içerenköy Mah.Alanaldi Cad. Özen Apt. No20 Anadolu Yakasi, Ataşehir');
INSERT INTO HEALTH_INSTITUTION ("tax_no", "build_name", "address") VALUES ('4119344889', 'ARİFOĞLU Eczanesi', 'Mutlukent Mah.2432 Cad. No:39/A Ümitköy/Çankaya/ANKARA');
INSERT INTO HEALTH_INSTITUTION ("tax_no", "build_name", "address") VALUES ('4945471796', 'KIVANÇ Eczanesi', 'Beyazıt Mah. Sevda Cad. No:4/B Akyurt/ ANKARA ');
INSERT INTO HEALTH_INSTITUTION ("tax_no", "build_name", "address") VALUES ('5409307949', 'İLDEN Eczanesi ', 'Nine Hatun Mah. Ayazma Cad. No: 50/1-A Esenler İstanbul');
INSERT INTO HEALTH_INSTITUTION ("tax_no", "build_name", "address") VALUES ('4679112901', 'ERDEM Eczanesi', 'Oruç Reis Mah. Gazi Cad. No: 50/B Esenler İstanbul');
INSERT INTO HEALTH_INSTITUTION ("tax_no", "build_name", "address") VALUES ('1932160227', 'Merve Eczanesi', 'Yüzyıl Mah. Barbaros Cad. 57. Sok. No: 39/A İstanbul');
INSERT INTO HEALTH_INSTITUTION ("tax_no", "build_name", "address") VALUES ('8275700945', 'Polat Eczanesi', 'Birlik Mah. Kazım Karabekir Cad. No: 144 Aşağı Karabayır Esenler İstanbul');
INSERT INTO HEALTH_INSTITUTION ("tax_no", "build_name", "address") VALUES ('6181404626', 'Demir Eczanesi', 'Oruçreis Mah. Barbaros Cad. 550. Sok. No:1 Yüzyıl Esenler İstanbul');
INSERT INTO HEALTH_INSTITUTION ("tax_no", "build_name", "address") VALUES ('5232643323', 'Bahadır Eczanesi', 'Fevzi Çakmak Mah. Atışalanı Cad. No: 120 Sondurak Esenler İstanbul');
INSERT INTO HEALTH_INSTITUTION ("tax_no", "build_name", "address") VALUES ('6823207778', 'Erdoğan Eczanesi', 'Kazım Karabekir Cad. No: 82/A İstanbul');
INSERT INTO HEALTH_INSTITUTION ("tax_no", "build_name", "address") VALUES ('1740198379', 'Kadircan Eczanesi', 'Ã‡amlÄ±ca Mah. Anadolu BulvarÄ± 149. Sok Regnum Ä°s Merkezi 16B No:4, 06200 Yenimahalle/Ankara');
INSERT INTO HEALTH_INSTITUTION ("tax_no", "build_name", "address") VALUES ('6454884655', 'SelÃ§uk Ecza Deposu', 'Macun, 177. Cd 19/F-2, 06374 Yenimahalle/Ankara');
INSERT INTO HEALTH_INSTITUTION ("tax_no", "build_name", "address") VALUES ('3974822025', 'PHARMATÃœRK ECZA DEPO', 'Ä°OSB 1333. Cadde No:46, 06378 Yenimahalle/Ankara');
INSERT INTO HEALTH_INSTITUTION ("tax_no", "build_name", "address") VALUES ('8117202345', 'Ares Ecza Deposu', 'Mutlukent, 1978. Cd. No:12, 06810 Ã‡ankaya/Ankara');
INSERT INTO HEALTH_INSTITUTION ("tax_no", "build_name", "address") VALUES ('2246014904', 'Ankyra Ecza Deposu', 'ZÃ¼beyde HanÄ±m, ZÃ¼beyde HanÄ±m Mahallesi SulugÃ¶z Sokak 11/A, 06060 Ä°skitler/AltÄ±ndaÄŸ/Ankara');
INSERT INTO HEALTH_INSTITUTION ("tax_no", "build_name", "address") VALUES ('2272897665', 'BaÅŸkent Cihan Ecza Deposu', '19 MayÄ±s, 19 MayÄ±s Cd. No:50, 06290 KeÃ§iÃ¶ren/Ankara');
