INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Bacitracin','Abbott','oral','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Baclofen','BD','syrup','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Bactrim','Apotex','tablet','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Bactrim DS','Abdi Ibrahim','pills','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Bactroban','BD','pills','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Basaglar','Lilly','syrup','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Belbuca','BD','tablet','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Belsomra','GSK','tablet','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Benadryl','Apotex','syrup','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Benazepril','Sanovel','oral','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Benicar','Abdi Ibrahim','spray','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Bentyl','GSK','pills','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Benzonatate','Lilly','pills','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Benztropine','Sanovel','tablet','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Betamethasone','Allergan','topical gel','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Bethanechol','Apotex','topical gel','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Bevacizumab','Sanofi','syrup','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Biaxin','Abdi Ibrahim','syrup','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Bicalutamide','Allergan','syrup','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Biktarvy','Phizer','topical gel','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Biotin','Apotex','spray','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Bisacodyl','Abbott','syrup','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Bismuth subsalicylate','Lilly','spray','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Bisoprolol','Abdi Ibrahim','topical gel','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Boniva','Sanovel','pills','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Botox','Sanovel','topical gel','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Breo Ellipta','Lilly','tablet','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Brilinta','Abbott','oral','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Brimonidine','BD','topical gel','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Budesonide','GSK','syrup','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Budesonide and Formoterol','Abbott','spray','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Bumetanide','GSK','topical gel','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Bumex','Allergan','topical gel','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Buprenorphine','Lilly','topical gel','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Buprenorphine and Naloxone','Sanovel','syrup','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Bupropion','Sanovel','pills','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Buspar','GSK','pills','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Buspirone','Lilly','oral','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Debrox','Apotex','syrup','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Decadron','Allergan','pills','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Demerol','BD','topical gel','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Denosumab','Lilly','oral','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Depakote','Apotex','topical gel','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Depo-Provera','GSK','spray','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Desloratadine','Phizer','spray','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Desvenlafaxine','Abdi Ibrahim','tablet','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Dexamethasone','Apotex','oral','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Dexilant','Lilly','oral','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Dextroamphetamine','GSK','pills','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Dextromethorphan','BD','oral','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Diazepam','Sanofi','oral','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Diclofenac','Sanovel','spray','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Diclofenac Sodium','Abdi Ibrahim','pills','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Dicyclomine','BD','pills','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Diflucan','Sanofi','tablet','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Digoxin','Lilly','tablet','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Dilantin','Sanofi','oral','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Dilaudid','Apotex','spray','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Diltiazem','Lilly','topical gel','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Diovan','BD','oral','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Diphenhydramine','Sanofi','tablet','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Ditropan','Sanovel','syrup','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Divalproex','Phizer','topical gel','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Divalproex sodium','Phizer','pills','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Docusate','Abbott','syrup','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Docusate Sodium','Abbott','pills','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Domperidone','GSK','topical gel','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Donepezil','Apotex','pills','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Doxazosin','Allergan','tablet','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Doxepin','Allergan','pills','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Doxycycline','Phizer','spray','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Dulcolax','Sanofi','spray','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Dulera','GSK','syrup','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Duloxetine','Phizer','tablet','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('DuoNeb','Apotex','syrup','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Dupixent','Apotex','topical gel','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Dutasteride','GSK','tablet','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Dyazide','Lilly','topical gel','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Echinacea','BD','tablet','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Ecotrin','Lilly','tablet','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Effexor','Sanofi','pills','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Effexor XR','GSK','pills','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Effient','Lilly','tablet','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Elavil','Phizer','oral','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Eligard','BD','topical gel','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Eliquis','Abbott','pills','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Elmiron','Apotex','oral','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Emgality','Allergan','spray','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Empagliflozin','Phizer','spray','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Enalapril','Sanovel','pills','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Enbrel','Sanovel','topical gel','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Enoxaparin','Sanovel','syrup','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Entecavir','Lilly','topical gel','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Entresto','Lilly','topical gel','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Entyvio','GSK','tablet','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Epclusa','Abbott','syrup','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Ephedrine','BD','syrup','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Epidiolex','Apotex','pills','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Epinephrine','Abbott','spray','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('EpiPen','BD','syrup','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Eplerenone','Lilly','spray','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Ergocalciferol','Allergan','topical gel','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Ertapenem','Phizer','syrup','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Erythromycin','Sanovel','topical gel','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Escitalopram','Phizer','syrup','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Esomeprazole','BD','syrup','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Estrace','Sanofi','spray','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Estradiol','Phizer','topical gel','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Eszopiclone','GSK','topical gel','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Ethambutol','Sanofi','spray','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Etodolac','Abbott','topical gel','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Eucrisa','Abbott','oral','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Evista','Abdi Ibrahim','topical gel','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Excedrin','Abdi Ibrahim','topical gel','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Exelon','Allergan','syrup','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Exemestane','Allergan','syrup','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Exforge','Allergan','topical gel','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Ezetimibe','Sanovel','oral','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Jadelle','GSK','topical gel','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Jadenu','Allergan','syrup','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Jakafi','Sanofi','spray','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Jalyn','Sanovel','syrup','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Jantoven','BD','spray','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Janumet','BD','topical gel','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Janumet XR','Apotex','oral','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Januvia','Apotex','spray','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Jardiance','Allergan','pills','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Jatenzo','Abdi Ibrahim','oral','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Jencycla','GSK','syrup','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Jentadueto','Sanofi','topical gel','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Jentadueto XR','Sanofi','oral','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Jetrea','BD','tablet','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Jeuveau','GSK','syrup','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Jevtana','Sanofi','oral','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Jiaogulan','Apotex','pills','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Jinteli','Abbott','tablet','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Jolessa','Allergan','syrup','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Jolivette','Abdi Ibrahim','syrup','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Jornay PM','Sanofi','syrup','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Jublia','Allergan','spray','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Juleber','Allergan','spray','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Juluca','Apotex','pills','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Junel','Sanovel','pills','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Junel 1/20','Abdi Ibrahim','topical gel','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Junel Fe 1/20','BD','pills','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Junel Fe 1.5/30','GSK','pills','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Junel Fe 24','BD','syrup','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Juvederm','BD','oral','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Juxtapid','Sanofi','spray','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Jynarque','Abdi Ibrahim','tablet','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Kadcyla','Abbott','syrup','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Kadian','Allergan','topical gel','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Kaletra','Phizer','tablet','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Kaopectate','Abbott','tablet','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Kapvay','Abbott','oral','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Kariva','Apotex','pills','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Kava','Sanovel','pills','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Kayexalate','GSK','oral','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Kcentra','Allergan','syrup','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('K-Dur','BD','syrup','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Keflex','Sanovel','oral','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Kenalog','Sanovel','oral','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Kenalog-40','Phizer','spray','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Keppra','Apotex','pills','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Keppra XR','Sanofi','tablet','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Ketamine','Abdi Ibrahim','topical gel','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Ketoconazole','Lilly','tablet','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Ketoconazole Cream','Phizer','spray','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Ketoconazole Shampoo','Abdi Ibrahim','spray','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Ketoconazole topical','Allergan','tablet','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Ketoprofen','Abbott','spray','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Ketorolac','BD','tablet','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Ketorolac ophthalmic','Sanovel','pills','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Ketorolac Tromethamine','Sanovel','spray','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Ketotifen','Allergan','topical gel','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Ketotifen ophthalmic','Abdi Ibrahim','topical gel','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Kevzara','Apotex','topical gel','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Keytruda','BD','spray','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Kineret','Sanovel','oral','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Kisqali','Sanovel','tablet','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Klonopin','Abdi Ibrahim','pills','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Klor-Con','Phizer','pills','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Kombiglyze XR','Sanofi','topical gel','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Korlym','Lilly','tablet','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Kratom','GSK','topical gel','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Krill Oil','Phizer','topical gel','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Krystexxa','BD','tablet','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('K-Tab','Abdi Ibrahim','oral','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Kyleena','Sanovel','topical gel','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Kyprolis','Abdi Ibrahim','topical gel','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Macrobid','Apotex','topical gel','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Magnesium','GSK','tablet','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Magnesium citrate','Allergan','topical gel','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Magnesium oxide','GSK','pills','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Meclizine','Phizer','topical gel','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Medrol','Abdi Ibrahim','spray','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Medrol Dosepak','Abdi Ibrahim','syrup','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Melatonin','Sanovel','pills','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Meloxicam','Sanovel','tablet','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Memantine','Allergan','tablet','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Meropenem','Apotex','oral','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Mesalamine','Abdi Ibrahim','tablet','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Metamucil','Abdi Ibrahim','syrup','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Metformin','BD','spray','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Methadone','Phizer','tablet','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Methimazole','BD','oral','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Methocarbamol','Abdi Ibrahim','topical gel','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Methotrexate','Sanovel','syrup','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Methylphenidate','Apotex','topical gel','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Methylprednisolone','Apotex','pills','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Metoclopramide','BD','syrup','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Metolazone','Sanovel','pills','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Metoprolol','Lilly','tablet','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Metoprolol Tartrate','Abbott','syrup','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Metronidazole','BD','tablet','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Midazolam','Apotex','tablet','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Midodrine','Sanofi','pills','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Minocycline','Lilly','pills','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('MiraLAX','Abbott','oral','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Mirapex','Allergan','spray','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Mirtazapine','Sanovel','spray','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Mobic','BD','syrup','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Modafinil','Lilly','spray','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Montelukast','Phizer','tablet','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Morphine','Sanofi','tablet','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Motrin','Apotex','topical gel','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Mucinex','Allergan','syrup','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Mupirocin','GSK','oral','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Mupirocin topical','Abbott','topical gel','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Myrbetriq','Apotex','syrup','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Ocrelizumab','Phizer','spray','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Ocrevus','Phizer','pills','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Octreotide','Abdi Ibrahim','spray','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Ocuflox','Abdi Ibrahim','oral','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Ocuvite','Phizer','topical gel','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Ofev','Abbott','spray','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Ofloxacin','Lilly','tablet','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Ofloxacin ophthalmic','Allergan','pills','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Olanzapine','Abbott','oral','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Olaparib','Sanofi','syrup','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Olmesartan','GSK','topical gel','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Olmesartan Medoxomil','Phizer','syrup','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Omalizumab','Sanofi','tablet','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Omega-3 polyunsaturated fatty acids','Abbott','spray','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Omeprazole','Abbott','syrup','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Omnicef','Apotex','tablet','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Ondansetron','GSK','tablet','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Onfi','Abbott','tablet','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Onglyza','GSK','topical gel','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Opana','Apotex','topical gel','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Opdivo','Sanofi','oral','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Opium','GSK','oral','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Orencia','Sanofi','spray','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Orlistat','Allergan','topical gel','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Orphenadrine','Sanovel','syrup','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Ortho Tri-Cyclen','Apotex','topical gel','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Oseltamivir','Phizer','tablet','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Otezla','Sanofi','spray','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Oxaliplatin','GSK','tablet','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Oxazepam','Phizer','topical gel','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Oxcarbazepine','Abdi Ibrahim','topical gel','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Oxybutynin','Phizer','syrup','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Oxycodone','Sanofi','tablet','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Oxycodone Hydrochloride','Allergan','spray','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Oxycontin','Sanofi','tablet','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Oxygen','Sanovel','pills','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Oxymetazoline nasal','Phizer','topical gel','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Oxymorphone','Abbott','pills','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Oxytocin','Sanovel','tablet','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Ozempic','Sanovel','oral','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Salbutamol','Abdi Ibrahim','spray','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Saw Palmetto','Abbott','tablet','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Saxenda','Allergan','topical gel','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Scopolamine','Sanofi','spray','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Selenium','Lilly','oral','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Senna','Apotex','syrup','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Senokot','Lilly','topical gel','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Sensipar','Sanofi','spray','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Septra','Sanovel','syrup','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Seroquel','Abbott','topical gel','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Sertraline','Abdi Ibrahim','syrup','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Sevelamer','Sanovel','tablet','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Shingrix','BD','tablet','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Sildenafil','Phizer','pills','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Simethicone','BD','spray','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Simvastatin','Sanovel','oral','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Sinemet','Allergan','oral','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Singulair','BD','pills','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Sitagliptin','BD','topical gel','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Skelaxin','Abdi Ibrahim','spray','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Sodium bicarbonate','Apotex','tablet','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Sodium chloride','Phizer','spray','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Solifenacin','Apotex','oral','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Solu-Medrol','Apotex','tablet','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Soma','Lilly','spray','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Sotalol','Phizer','spray','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Spiriva','Abbott','tablet','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Spironolactone','GSK','pills','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Stelara','GSK','pills','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Strattera','Phizer','topical gel','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Suboxone','Abbott','oral','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Subutex','Lilly','topical gel','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Sucralfate','Sanovel','pills','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Sudafed','Abbott','topical gel','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Sulfamethoxazole and trimethoprim','Allergan','spray','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Sulfasalazine','Allergan','oral','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Sumatriptan','Abdi Ibrahim','topical gel','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Symbicort','BD','tablet','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Synthroid','GSK','syrup','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Systane','Lilly','oral','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Ubiquinone','Phizer','oral','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Uceris','Abbott','topical gel','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Udenyca','Abbott','pills','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Ulesfia','Abdi Ibrahim','topical gel','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Ulipristal','Abdi Ibrahim','pills','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Uloric','Sanovel','tablet','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Ultomiris','Allergan','oral','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Ultracet','Lilly','tablet','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Ultram','GSK','topical gel','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Ultram ER','Lilly','syrup','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Ultravate','Apotex','syrup','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Ultresa','Sanofi','oral','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Umeclidinium','Abbott','syrup','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Umeclidinium and vilanterol','Sanofi','spray','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Unasyn','Apotex','tablet','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Undecylenic acid topical','Abdi Ibrahim','spray','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Unisom','Sanofi','topical gel','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Unisom SleepMelts','Lilly','topical gel','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Unithroid','Abbott','syrup','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Univasc','Abdi Ibrahim','topical gel','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Upadacitinib','Sanovel','tablet','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Uptravi','Allergan','pills','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Ureacin-10','GSK','tablet','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Urea Cream','GSK','syrup','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Urecholine','Sanovel','syrup','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Uribel','Sanovel','tablet','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Urimar-T','Apotex','spray','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Urin D/S','BD','syrup','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Urispas','GSK','topical gel','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Uristat','Abdi Ibrahim','topical gel','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Urocit-K','Abdi Ibrahim','oral','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Urogesic-Blue','Sanovel','spray','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Urokinase','Apotex','spray','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Uro-MP','BD','syrup','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Uroxatral','Allergan','topical gel','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Urso','Phizer','oral','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Ursodiol','Abbott','syrup','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Ustekinumab','Abbott','topical gel','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Utibron Neohaler','Lilly','pills','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Uva Ursi','BD','syrup','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Valacyclovir','Phizer','oral','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Valium','Lilly','tablet','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Valproic acid','GSK','syrup','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Valsartan','Sanofi','topical gel','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Valtrex','Allergan','spray','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Vancomycin','Phizer','oral','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Varenicline','Lilly','syrup','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Vascepa','Sanovel','spray','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Vasopressin','Lilly','topical gel','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Vasotec','BD','tablet','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Veltassa','Allergan','spray','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Venlafaxine','GSK','tablet','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Venofer','GSK','topical gel','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Ventolin','Abdi Ibrahim','syrup','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Ventolin HFA','Abdi Ibrahim','topical gel','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Verapamil','GSK','oral','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Versed','Abbott','syrup','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('VESIcare','GSK','tablet','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Viagra','Sanofi','topical gel','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Viberzi','Lilly','pills','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Vibramycin','Lilly','syrup','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Vicodin','Sanovel','spray','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Victoza','Lilly','tablet','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Vigamox','GSK','syrup','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Viibryd','Phizer','oral','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Vimpat','Phizer','topical gel','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Vistaril','Lilly','tablet','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Vitamin B 12','GSK','spray','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Vitamin C','Sanovel','oral','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Vitamin D','GSK','tablet','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Vitamin D2','Lilly','topical gel','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Vitamin D3','BD','tablet','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Vitamin E','GSK','oral','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Vivitrol','Abbott','syrup','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Voltaren','Abdi Ibrahim','topical gel','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Voltaren Gel','Allergan','pills','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Vortioxetine','Lilly','tablet','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Vraylar','Sanofi','pills','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Vytorin','Allergan','tablet','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Vyvanse','GSK','tablet','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Xadago','GSK','topical gel','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Xalatan','Sanovel','topical gel','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Xalkori','Lilly','syrup','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Xanax','Phizer','oral','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Xanax XR','GSK','spray','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Xarelto','Allergan','oral','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Xeljanz','Abdi Ibrahim','tablet','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Xeljanz XR','Sanovel','pills','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Xeloda','Sanofi','spray','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Xenazine','Abbott','oral','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Xenical','Apotex','spray','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Xenleta','Sanovel','spray','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Xeomin','Lilly','oral','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Xermelo','BD','syrup','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Xgeva','Allergan','spray','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Xhance','Abbott','tablet','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Xiaflex','Abbott','topical gel','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Xifaxan','Abbott','topical gel','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Xigduo XR','Apotex','syrup','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Xiidra','Sanofi','syrup','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Xofigo','Allergan','topical gel','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Xofluza','Abbott','oral','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Xolair','Sanovel','topical gel','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Xopenex','Lilly','oral','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Xopenex HFA','Apotex','spray','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Xospata','GSK','pills','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Xpovio','Allergan','topical gel','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Xrylix','Allergan','spray','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Xtampza ER','Phizer','pills','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Xtandi','Sanofi','spray','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Xulane','BD','spray','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Xultophy','Sanovel','spray','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Xylitol','GSK','topical gel','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Xylocaine','Phizer','pills','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Xylocaine Jelly','GSK','pills','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Xylometazoline','Apotex','spray','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Xylometazoline nasal','Abbott','spray','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Xyosted','Allergan','topical gel','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Xyrem','GSK','pills','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Xyzal','Phizer','syrup','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Yarrow','Lilly','tablet','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Yasmin','GSK','topical gel','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Yaz','Apotex','syrup','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Yervoy','Phizer','spray','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Yescarta','Abbott','tablet','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Yohimbe','Allergan','oral','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Yohimbine','Abdi Ibrahim','topical gel','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Yondelis','Lilly','topical gel','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Yonsa','GSK','tablet','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Yosprala','Lilly','topical gel','for infections',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Yupelri','Abbott','pills','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Yuvafem','Phizer','spray','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Zaditor','GSK','spray','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Zaleplon','Sanofi','oral','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Zanaflex','Sanofi','spray','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Zantac','Abdi Ibrahim','oral','for inflamations',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Zaroxolyn','GSK','topical gel','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Zarxio','Sanofi','topical gel','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Zebeta','GSK','spray','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Zegerid','Abbott','spray','for joint related aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Zenpep','Abdi Ibrahim','topical gel','for general use aches',' ');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse") VALUES ('Zestoretic','Abbott','topical gel','for inflamations',' ');
