INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Bacitracin','BD','pills','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Baclofen','Abbott','tablet','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Bactrim','Abdi Ibrahim','topical gel','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Bactrim DS','Sanofi','tablet','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Bactroban','Lilly','tablet','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Basaglar','GSK','tablet','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Belbuca','Abbott','tablet','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Belsomra','Abbott','spray','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Benadryl','Lilly','oral','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Benazepril','Apotex','spray','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Benicar','GSK','oral','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Bentyl','Abdi Ibrahim','topical gel','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Benzonatate','Sanovel','oral','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Benztropine','Abdi Ibrahim','tablet','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Betamethasone','Phizer','pills','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Bethanechol','Phizer','syrup','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Bevacizumab','GSK','spray','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Biaxin','Phizer','pills','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Bicalutamide','BD','topical gel','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Biktarvy','Lilly','topical gel','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Biotin','Apotex','tablet','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Bisacodyl','Sanofi','syrup','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Bismuth subsalicylate','Sanofi','topical gel','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Bisoprolol','Phizer','tablet','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Boniva','Phizer','topical gel','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Botox','Apotex','oral','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Breo Ellipta','Abdi Ibrahim','oral','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Brilinta','Abdi Ibrahim','syrup','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Brimonidine','Abbott','oral','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Budesonide','GSK','pills','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Budesonide and Formoterol','Lilly','tablet','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Bumetanide','BD','pills','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Bumex','BD','tablet','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Buprenorphine','Sanofi','spray','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Buprenorphine and Naloxone','Sanovel','oral','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Bupropion','Sanofi','spray','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Buspar','Phizer','spray','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Buspirone','BD','oral','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Debrox','BD','syrup','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Decadron','Allergan','spray','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Demerol','BD','spray','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Denosumab','Lilly','oral','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Depakote','Lilly','tablet','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Depo-Provera','GSK','tablet','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Desloratadine','BD','syrup','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Desvenlafaxine','Apotex','syrup','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Dexamethasone','Abbott','oral','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Dexilant','Lilly','syrup','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Dextroamphetamine','Sanovel','oral','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Dextromethorphan','Sanovel','spray','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Diazepam','Phizer','oral','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Diclofenac','GSK','oral','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Diclofenac Sodium','Apotex','spray','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Dicyclomine','Abbott','syrup','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Diflucan','Sanovel','oral','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Digoxin','Sanovel','syrup','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Dilantin','GSK','oral','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Dilaudid','BD','oral','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Diltiazem','Abbott','spray','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Diovan','Abbott','oral','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Diphenhydramine','Apotex','syrup','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Ditropan','Abdi Ibrahim','syrup','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Divalproex','Phizer','tablet','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Divalproex sodium','Apotex','spray','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Docusate','Sanovel','spray','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Docusate Sodium','BD','tablet','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Domperidone','Apotex','syrup','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Donepezil','BD','spray','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Doxazosin','Lilly','topical gel','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Doxepin','Sanovel','tablet','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Doxycycline','Phizer','topical gel','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Dulcolax','BD','tablet','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Dulera','Allergan','syrup','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Duloxetine','Allergan','topical gel','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('DuoNeb','Lilly','spray','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Dupixent','GSK','tablet','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Dutasteride','Abbott','oral','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Dyazide','Sanofi','pills','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Echinacea','BD','topical gel','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Ecotrin','Allergan','pills','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Effexor','Sanofi','syrup','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Effexor XR','Apotex','pills','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Effient','Phizer','topical gel','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Elavil','Abbott','syrup','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Eligard','Sanovel','spray','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Eliquis','Allergan','spray','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Elmiron','Phizer','spray','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Emgality','Sanofi','spray','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Empagliflozin','Phizer','spray','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Enalapril','BD','oral','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Enbrel','Apotex','syrup','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Enoxaparin','GSK','syrup','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Entecavir','Abbott','tablet','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Entresto','Phizer','syrup','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Entyvio','BD','tablet','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Epclusa','Sanofi','topical gel','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Ephedrine','Abdi Ibrahim','tablet','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Epidiolex','GSK','syrup','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Epinephrine','Abbott','tablet','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('EpiPen','GSK','syrup','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Eplerenone','Sanovel','oral','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Ergocalciferol','Abdi Ibrahim','syrup','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Ertapenem','Apotex','oral','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Erythromycin','Apotex','syrup','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Escitalopram','Sanofi','pills','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Esomeprazole','Allergan','spray','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Estrace','GSK','pills','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Estradiol','Sanovel','topical gel','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Eszopiclone','Apotex','tablet','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Ethambutol','Lilly','oral','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Etodolac','Sanovel','topical gel','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Eucrisa','Sanovel','tablet','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Evista','GSK','topical gel','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Excedrin','Sanofi','spray','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Exelon','Apotex','topical gel','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Exemestane','Lilly','pills','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Exforge','Abdi Ibrahim','topical gel','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Ezetimibe','Phizer','syrup','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Jadelle','GSK','tablet','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Jadenu','Phizer','spray','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Jakafi','Apotex','oral','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Jalyn','Allergan','spray','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Jantoven','Lilly','tablet','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Janumet','Sanovel','oral','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Janumet XR','GSK','topical gel','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Januvia','Lilly','oral','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Jardiance','Abbott','oral','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Jatenzo','Allergan','tablet','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Jencycla','Allergan','tablet','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Jentadueto','Lilly','syrup','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Jentadueto XR','Allergan','topical gel','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Jetrea','Lilly','oral','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Jeuveau','BD','pills','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Jevtana','Allergan','oral','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Jiaogulan','Sanovel','spray','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Jinteli','Apotex','syrup','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Jolessa','Phizer','pills','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Jolivette','Phizer','pills','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Jornay PM','Sanofi','oral','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Jublia','Allergan','topical gel','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Juleber','Allergan','pills','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Juluca','Abbott','topical gel','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Junel','Phizer','topical gel','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Junel 1/20','Abbott','oral','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Junel Fe 1/20','Abdi Ibrahim','topical gel','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Junel Fe 1.5/30','Apotex','spray','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Junel Fe 24','Phizer','tablet','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Juvederm','Abdi Ibrahim','oral','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Juxtapid','Sanofi','topical gel','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Jynarque','Abbott','syrup','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Kadcyla','Apotex','tablet','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Kadian','Abbott','topical gel','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Kaletra','Abdi Ibrahim','pills','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Kaopectate','Abdi Ibrahim','oral','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Kapvay','BD','tablet','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Kariva','Sanovel','spray','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Kava','Allergan','topical gel','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Kayexalate','Sanofi','tablet','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Kcentra','Apotex','spray','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('K-Dur','Abdi Ibrahim','pills','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Keflex','Sanofi','syrup','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Kenalog','Sanovel','oral','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Kenalog-40','Lilly','syrup','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Keppra','Lilly','topical gel','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Keppra XR','Lilly','syrup','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Ketamine','Abdi Ibrahim','oral','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Ketoconazole','Allergan','tablet','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Ketoconazole Cream','Abdi Ibrahim','oral','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Ketoconazole Shampoo','Lilly','tablet','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Ketoconazole topical','Sanovel','pills','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Ketoprofen','BD','tablet','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Ketorolac','Sanofi','spray','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Ketorolac ophthalmic','Phizer','topical gel','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Ketorolac Tromethamine','BD','oral','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Ketotifen','Allergan','topical gel','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Ketotifen ophthalmic','Allergan','pills','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Kevzara','Apotex','oral','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Keytruda','Phizer','syrup','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Kineret','GSK','spray','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Kisqali','Apotex','spray','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Klonopin','Abbott','spray','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Klor-Con','Lilly','tablet','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Kombiglyze XR','Abdi Ibrahim','topical gel','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Korlym','Apotex','spray','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Kratom','BD','syrup','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Krill Oil','Apotex','topical gel','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Krystexxa','Apotex','syrup','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('K-Tab','Allergan','syrup','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Kyleena','Allergan','tablet','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Kyprolis','Lilly','tablet','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Macrobid','Allergan','spray','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Magnesium','Sanofi','tablet','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Magnesium citrate','Apotex','syrup','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Magnesium oxide','Phizer','tablet','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Meclizine','Sanofi','oral','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Medrol','Abbott','pills','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Medrol Dosepak','Sanovel','pills','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Melatonin','Lilly','spray','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Meloxicam','Lilly','spray','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Memantine','Apotex','oral','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Meropenem','Apotex','spray','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Mesalamine','Abbott','oral','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Metamucil','Abbott','topical gel','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Metformin','BD','syrup','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Methadone','Sanovel','oral','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Methimazole','BD','topical gel','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Methocarbamol','Allergan','syrup','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Methotrexate','GSK','spray','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Methylphenidate','Sanofi','oral','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Methylprednisolone','Abdi Ibrahim','pills','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Metoclopramide','Lilly','syrup','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Metolazone','Abbott','topical gel','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Metoprolol','BD','spray','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Metoprolol Tartrate','Allergan','tablet','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Metronidazole','Apotex','tablet','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Midazolam','Sanofi','pills','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Midodrine','GSK','syrup','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Minocycline','Apotex','oral','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('MiraLAX','Sanofi','pills','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Mirapex','Sanofi','tablet','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Mirtazapine','Lilly','tablet','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Mobic','Abbott','topical gel','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Modafinil','Sanovel','oral','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Montelukast','Abdi Ibrahim','pills','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Morphine','Lilly','oral','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Motrin','BD','oral','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Mucinex','Phizer','tablet','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Mupirocin','Phizer','spray','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Mupirocin topical','Apotex','oral','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Myrbetriq','Phizer','tablet','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Ocrelizumab','Abbott','topical gel','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Ocrevus','Lilly','topical gel','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Octreotide','Phizer','spray','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Ocuflox','Apotex','pills','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Ocuvite','Lilly','topical gel','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Ofev','Allergan','pills','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Ofloxacin','GSK','pills','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Ofloxacin ophthalmic','Allergan','spray','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Olanzapine','Lilly','pills','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Olaparib','Sanovel','syrup','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Olmesartan','Abdi Ibrahim','oral','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Olmesartan Medoxomil','BD','spray','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Omalizumab','Abdi Ibrahim','tablet','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Omega-3 polyunsaturated fatty acids','BD','syrup','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Omeprazole','Sanovel','syrup','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Omnicef','BD','syrup','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Ondansetron','BD','topical gel','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Onfi','Abbott','oral','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Onglyza','Sanofi','spray','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Opana','BD','oral','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Opdivo','Sanofi','syrup','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Opium','Phizer','spray','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Orencia','Apotex','pills','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Orlistat','Allergan','syrup','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Orphenadrine','Abbott','tablet','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Ortho Tri-Cyclen','Apotex','oral','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Oseltamivir','GSK','syrup','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Otezla','Abbott','spray','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Oxaliplatin','Abbott','spray','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Oxazepam','Allergan','syrup','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Oxcarbazepine','Sanofi','topical gel','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Oxybutynin','GSK','pills','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Oxycodone','Abdi Ibrahim','oral','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Oxycodone Hydrochloride','Phizer','tablet','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Oxycontin','Sanovel','tablet','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Oxygen','BD','syrup','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Oxymetazoline nasal','Abdi Ibrahim','topical gel','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Oxymorphone','Abbott','topical gel','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Oxytocin','Sanofi','oral','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Ozempic','Abdi Ibrahim','syrup','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Salbutamol','Sanovel','pills','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Saw Palmetto','Apotex','topical gel','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Saxenda','Apotex','oral','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Scopolamine','Abdi Ibrahim','spray','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Selenium','Sanofi','syrup','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Senna','Abbott','topical gel','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Senokot','BD','oral','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Sensipar','BD','topical gel','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Septra','Phizer','syrup','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Seroquel','BD','topical gel','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Sertraline','Lilly','pills','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Sevelamer','BD','pills','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Shingrix','Abdi Ibrahim','spray','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Sildenafil','Sanovel','tablet','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Simethicone','Abdi Ibrahim','tablet','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Simvastatin','Abdi Ibrahim','tablet','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Sinemet','Apotex','oral','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Singulair','Allergan','tablet','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Sitagliptin','Abdi Ibrahim','spray','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Skelaxin','GSK','topical gel','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Sodium bicarbonate','Sanofi','topical gel','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Sodium chloride','Abbott','spray','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Solifenacin','Phizer','pills','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Solu-Medrol','Abdi Ibrahim','syrup','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Soma','Phizer','tablet','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Sotalol','Phizer','oral','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Spiriva','Abbott','topical gel','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Spironolactone','BD','spray','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Stelara','Phizer','pills','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Strattera','Sanofi','tablet','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Suboxone','Sanovel','oral','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Subutex','Phizer','oral','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Sucralfate','GSK','pills','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Sudafed','Phizer','topical gel','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Sulfamethoxazole and trimethoprim','Abbott','oral','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Sulfasalazine','Sanovel','syrup','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Sumatriptan','Apotex','topical gel','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Symbicort','GSK','tablet','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Synthroid','BD','syrup','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Systane','Abdi Ibrahim','topical gel','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Ubiquinone','Allergan','tablet','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Uceris','Abdi Ibrahim','pills','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Udenyca','Allergan','pills','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Ulesfia','Allergan','syrup','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Ulipristal','BD','tablet','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Uloric','Lilly','syrup','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Ultomiris','Lilly','syrup','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Ultracet','Abdi Ibrahim','syrup','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Ultram','Abdi Ibrahim','spray','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Ultram ER','Sanovel','oral','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Ultravate','Lilly','pills','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Ultresa','Allergan','oral','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Umeclidinium','Abdi Ibrahim','pills','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Umeclidinium and vilanterol','Abdi Ibrahim','spray','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Unasyn','Allergan','syrup','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Undecylenic acid topical','Apotex','topical gel','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Unisom','Sanovel','spray','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Unisom SleepMelts','Sanofi','topical gel','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Unithroid','BD','oral','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Univasc','Abbott','pills','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Upadacitinib','GSK','spray','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Uptravi','BD','spray','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Ureacin-10','Abbott','oral','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Urea Cream','Apotex','topical gel','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Urecholine','Sanofi','oral','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Uribel','Sanofi','syrup','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Urimar-T','Sanofi','spray','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Urin D/S','GSK','oral','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Urispas','Allergan','oral','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Uristat','Phizer','pills','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Urocit-K','BD','syrup','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Urogesic-Blue','Allergan','pills','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Urokinase','Lilly','syrup','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Uro-MP','Abbott','tablet','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Uroxatral','Sanovel','pills','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Urso','GSK','syrup','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Ursodiol','Apotex','tablet','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Ustekinumab','Lilly','oral','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Utibron Neohaler','Abbott','spray','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Uva Ursi','Abdi Ibrahim','syrup','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Valacyclovir','Allergan','topical gel','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Valium','Sanofi','tablet','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Valproic acid','Sanovel','oral','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Valsartan','Lilly','oral','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Valtrex','Sanofi','topical gel','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Vancomycin','BD','topical gel','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Varenicline','Abdi Ibrahim','spray','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Vascepa','Phizer','topical gel','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Vasopressin','Phizer','syrup','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Vasotec','Lilly','pills','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Veltassa','Apotex','spray','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Venlafaxine','Abdi Ibrahim','pills','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Venofer','Sanofi','topical gel','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Ventolin','Abbott','syrup','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Ventolin HFA','GSK','oral','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Verapamil','Abbott','syrup','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Versed','Abbott','tablet','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('VESIcare','Sanofi','syrup','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Viagra','Apotex','tablet','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Viberzi','Allergan','oral','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Vibramycin','GSK','tablet','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Vicodin','Phizer','tablet','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Victoza','Lilly','spray','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Vigamox','Sanofi','spray','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Viibryd','Sanofi','spray','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Vimpat','Abdi Ibrahim','tablet','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Vistaril','Abdi Ibrahim','oral','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Vitamin B 12','Lilly','pills','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Vitamin C','Phizer','oral','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Vitamin D','Phizer','spray','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Vitamin D2','Sanovel','topical gel','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Vitamin D3','Lilly','tablet','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Vitamin E','Abbott','pills','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Vivitrol','Apotex','pills','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Voltaren','Abbott','tablet','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Voltaren Gel','Abdi Ibrahim','syrup','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Vortioxetine','GSK','oral','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Vraylar','Abdi Ibrahim','spray','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Vytorin','BD','topical gel','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Vyvanse','Phizer','pills','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Xadago','Sanovel','oral','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Xalatan','BD','syrup','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Xalkori','Apotex','pills','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Xanax','GSK','oral','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Xanax XR','Phizer','tablet','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Xarelto','Sanofi','pills','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Xeljanz','BD','tablet','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Xeljanz XR','Sanofi','pills','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Xeloda','Phizer','tablet','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Xenazine','Sanofi','syrup','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Xenical','Sanovel','pills','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Xenleta','Allergan','pills','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Xeomin','Apotex','syrup','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Xermelo','Phizer','tablet','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Xgeva','Lilly','syrup','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Xhance','Lilly','syrup','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Xiaflex','GSK','syrup','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Xifaxan','Sanovel','spray','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Xigduo XR','Phizer','tablet','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Xiidra','Abbott','spray','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Xofigo','Abdi Ibrahim','spray','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Xofluza','Abbott','oral','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Xolair','Abdi Ibrahim','pills','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Xopenex','Allergan','topical gel','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Xopenex HFA','Sanovel','tablet','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Xospata','Lilly','tablet','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Xpovio','Sanovel','pills','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Xrylix','Sanovel','spray','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Xtampza ER','Apotex','oral','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Xtandi','Abdi Ibrahim','spray','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Xulane','Sanovel','pills','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Xultophy','Sanofi','topical gel','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Xylitol','Allergan','spray','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Xylocaine','Apotex','topical gel','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Xylocaine Jelly','Lilly','pills','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Xylometazoline','Apotex','topical gel','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Xylometazoline nasal','Allergan','oral','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Xyosted','Phizer','topical gel','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Xyrem','GSK','tablet','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Xyzal','BD','syrup','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Yarrow','Abdi Ibrahim','spray','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Yasmin','Apotex','pills','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Yaz','Abdi Ibrahim','pills','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Yervoy','Apotex','pills','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Yescarta','Sanovel','topical gel','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Yohimbe','Allergan','tablet','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Yohimbine','BD','topical gel','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Yondelis','Apotex','tablet','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Yonsa','Sanofi','tablet','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Yosprala','Allergan','topical gel','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Yupelri','Allergan','topical gel','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Yuvafem','Abbott','oral','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Zaditor','Lilly','tablet','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Zaleplon','Allergan','oral','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Zanaflex','Abbott','syrup','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Zantac','Allergan','tablet','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Zaroxolyn','Abdi Ibrahim','oral','for joint related aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Zarxio','Abdi Ibrahim','pills','for infections');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Zebeta','Allergan','oral','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Zegerid','Sanofi','syrup','for inflamations');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Zenpep','BD','oral','for general use aches');
INSERT INTO MEDICINE_PROPS ("mname", "brand", "pack_form", "use_type", "howtouse",) VALUES ('Zestoretic','Abbott','syrup','for joint related aches');
